# Generated by Django 6.1 on 2026-08-09 10:47

import analytics.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleaned_file', models.FileField(blank=True, null=True, upload_to=analytics.models.dataset_cleaned_path)),
                ('rows', models.IntegerField(default=0)),
                ('columns', models.IntegerField(default=0)),
                ('quality_score', models.IntegerField(default=100)),
                ('profile', models.JSONField(blank=True, default=dict)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('file_meta', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pages', models.JSONField(default=list)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=analytics.models.report_pdf_path)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='analytics.dataset')),
            ],
        ),
    ]
